version: '3.1'

services:
  db:
    image: mongo
    restart: always
    volumes:
      - type: bind
        source: ./database
        target: /data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    networks:
      - internal

  app:
    build: .
    restart: always
    ports:
      - "3001:3001"
    depends_on:
      - db
    environment:
      BOT_TOKEN: ${BOT_TOKEN}
      DATABASE_URL: ${MONGO_URL}
    networks:
      - internal

networks:
  internal:
    driver: bridge
